# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/JanJiang92/JanJiang92.github.io.git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: master
